export function packageJsonTemplate(name: string): string {
  return JSON.stringify(
    {
      name,
      version: '0.1.0',
      private: true,
      engines: {
        node: '>=18.0.0',
        npm: '>=9.0.0',
      },
      scripts: {
        dev: 'next dev',
        build: 'next build',
        start: 'next start',
        lint: 'eslint',
        prettier: 'prettier --write .',
        prepare: 'husky',
        test: 'jest',
        'test:watch': 'jest --watch',
      },
      dependencies: {
        'lucide-react': '^0.474.0',
        next: '15.3.2',
        react: '19.1.0',
        'react-dom': '19.1.0',
        zustand: '^5.0.11',
      },
      devDependencies: {
        '@commitlint/cli': '^20.4.2',
        '@commitlint/config-conventional': '^20.4.2',
        '@commitlint/types': '^20.4.0',
        '@tailwindcss/postcss': '^4',
        '@testing-library/jest-dom': '^6.9.1',
        '@testing-library/react': '^16.3.2',
        '@testing-library/user-event': '^14.6.1',
        '@types/jest': '^30.0.0',
        '@types/node': '^20',
        '@types/react': '^19',
        '@types/react-dom': '^19',
        eslint: '^9',
        'eslint-config-next': '15.3.2',
        husky: '^9.1.7',
        jest: '^30.0.0',
        'jest-environment-jsdom': '^30.0.0',
        prettier: '^3.8.1',
        tailwindcss: '^4',
        'ts-jest': '^29.4.9',
        typescript: '^5',
      },
    },
    null,
    2,
  );
}
